spring:
   liquibase:
      change-log: classpath:liquibase/master.xml
      enabled: true
   datasource:
      url: jdbc:postgresql://localhost:5432/moock
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: none
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
   mvc:
      cors:
         allowed-origins: "*"
         allowed-methods: "*"
         allowed-headers: "*"


server:
   port: 8080

logging:
   level:
      root: INFO
      com.example.package: DEBUG
   file: /server/log/mockpit.log
   configuration:
      status: warn
      appenders:
         - name: ConsoleAppender
           type: Console
           target: SYSTEM_OUT
           PatternLayout:
              pattern: "%d [%t] %-5level %logger{36} - %msg%n"
      loggers:
         - name: com.example.package
           level: DEBUG
           AppenderRef:
              - ref: ConsoleAppender

springdoc:
   swagger-ui:
      path: /swagger-ui.html
      enabled: true

   api-docs:
      path: /v3/api-docs
      enabled: true
      title: Mock Buddy API
      description: A REST Mock Server